#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#########################################################
#                                                       #
#           STATIC PAGES ROUTES                         #
#                                                       #
#########################################################

home:
    path: /
    controller: App\Controller\PageController::index
    
agent:
    path: /agent
    controller: App\Controller\PageController::agent
    
about:
    path: /about
    controller: App\Controller\PageController::about
    
blog:
    path: /blog
    controller: App\Controller\PageController::blog
    
contact:
    path: /contact
    controller: App\Controller\PageController::contact

#########################################################
#                                                       #
#           END STATIC PAGES ROUTES                     #
#                                                       #
#########################################################

#########################################################
#                                                       #
#           PROPERTY PAGES ROUTES                       #
#                                                       #
#########################################################

property.index:
    path: /property
    controller: App\Controller\PropertyController::index
    
property.show:
    path: /property/{slug}/{id}
    controller: App\Controller\PropertyController::show
    requirements:
        slug: '^[a-z-]+$'
        id: '[0-9]+'

#########################################################
#                                                       #
#           END PROPERTY PAGES ROUTES                   #
#                                                       #
#########################################################


#########################################################
#                                                       #
#           ADMIN PROPERTY PAGES ROUTES                 #
#                                                       #
#########################################################

admin.property.index:
    path: /admin/property
    controller: App\Controller\Admin\AdminPropertyController::index

admin.property.insert:
    path: /admin/property/insert
    controller: App\Controller\Admin\AdminPropertyController::insert

admin.property.edit:
    path: /admin/property/{id}
    controller: App\Controller\Admin\AdminPropertyController::edit
    methods: 'GET|POST'
    requirements:
        id: '[0-9]'
        
admin.property.delete:
    path: /admin/property/{id}
    controller: App\Controller\Admin\AdminPropertyController::delete
    methods: 'DELETE'
    requirements:
        id: '[0-9]+'

#########################################################
#                                                       #
#           END  ADMIN PROPERTY PAGES ROUTES            #
#                                                       #
#########################################################
